import { initMotionToggles } from './prefs.js';
import { initNav } from './ui/nav.js';
import { initTickets } from './ui/tickets.js';
import { initFaq } from './ui/faq.js';
import { initMedia } from './ui/media.js';
import { initDialogs } from './ui/dialog.js';
import { initWhatsApp } from './ui/whatsapp.js';
import { initSound } from './ui/sound.js';
import { startMotion } from './motion/index.js';
import { opening } from './motion/opening.js';
import { velocity } from './motion/velocity.js';
import { dolly } from './motion/dolly.js';
import { spotlight } from './motion/spotlight.js';
import { dust } from './motion/dust.js';
import { reveals } from './motion/reveals.js';
import { sceneLabels } from './motion/sceneLabels.js';
import { notu } from './motion/notu.js';
import { ticketsMotion } from './motion/tickets.js';
import { tilt } from './motion/tilt.js';
import { wipes } from './motion/wipes.js';
import { masks } from './motion/masks.js';
import { formats } from './motion/formats.js';
import { formatsWash } from './motion/formatsWash.js';
import { portrait } from './motion/portrait.js';
import { certificate } from './motion/certificate.js';
import { board } from './motion/board.js';
import { steps } from './motion/steps.js';
import { faqMotion } from './motion/faq.js';
import { houseDim } from './motion/houseDim.js';
import { marquee } from './motion/marquee.js';
import { finale } from './motion/finale.js';
import { followSpot } from './motion/followSpot.js';
import { initDebug } from './debug.js';

initMotionToggles();
initNav();
initTickets();
initFaq();
initMedia();
initDialogs();
initWhatsApp();
initSound();
document.querySelectorAll('[data-year]').forEach((el) => { el.textContent = String(new Date().getFullYear()); });

startMotion([velocity, opening, dolly, spotlight, dust, reveals, sceneLabels, notu, ticketsMotion, tilt, wipes, masks, formats, formatsWash, portrait, certificate, board, steps, faqMotion, houseDim, marquee, finale, followSpot]);
initDebug();
